<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminNavigation ?>

        <div class="title">Account home</div>

        <?php echo $this->messages() ?>

        </div><!-- End top area -->

        <div id="stage"><!-- Start stage area -->

            <p>Welcome to the ideastore.co.uk CMS, please use the menu above to navigate around the system.</p>

        </div><!-- End stage area -->

    </body>
</html>
