
                <fieldset>
                    <legend>Login</legend>

                    <?php echo $this->messages() ?>

                    <?php
                    $form = $this->form;
                    $form->setAttribute('class', 'form-horizontal');
                    $form->prepare();
                    ?>

                    <?php echo $this->form()->openTag($form) ?>

                        <?php echo $this->adminFormElement($form->get('redirect')) ?>
                        <?php echo $this->adminFormElement($form->get('username')) ?>
                        <?php echo $this->adminFormElement($form->get('password')) ?>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('login')->setAttribute('class', 'btn btn-primary');
                                echo $this->formElement($form->get('login'));
                                ?>

                            </div>
                        </div>

                    <?php echo $this->form()->closeTag() ?>

                </fieldset>
