
                <fieldset>
                    <legend>Login</legend>

                    <?php echo $this->messages() ?>

                    <?php
                    $form = $this->form;
                    $form->prepare();
                    ?>

                    <?php echo $this->form()->openTag($form) ?>

                        <?php echo $this->adminFormElement($form->get('redirect')) ?>
                        <?php echo $this->adminFormElement($form->get('username')) ?>
                        <?php echo $this->adminFormElement($form->get('password')) ?>

                        <div class="form-element">
                            <div class="form-inputs line-up">
                                <?php
                                $form->get('login')->setAttribute('class', 'button');
                                echo $this->formElement($form->get('login'));
                                ?>
                            </div>
                        </div>

                    <?php echo $this->form()->closeTag() ?>

                </fieldset>
